version: '3'
services:
  fpm:
    build: ./fpm
    tty: true
    working_dir: /var/www/syncer
    volumes:
      - ../.:/var/www/syncer:default
      - ./fpm/config/php.ini-local:/usr/local/etc/php/php.ini:ro

  nginx:
    image: nginx:stable-alpine
    working_dir: /var/www/syncer
    ports:
      - "80:80"
    volumes:
      - ../.:/var/www/syncer:default
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:default

  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=syncer
      - MYSQL_USER=syncer
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
    ports:
      - "8002:6379"

volumes:
  mysql_data:
